# Generated by Django 4.2 on 2023-05-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0011_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscore',
            name='center_code',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='examscore',
            name='subject',
            field=models.CharField(default='', max_length=500),
        ),
    ]
