# Generated by Django 4.2 on 2023-05-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0012_examscore_center_code_examscore_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_code', models.CharField(max_length=500)),
                ('exam_id', models.IntegerField()),
                ('exam_name', models.CharField(max_length=255)),
                ('classes', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('roll_no', models.CharField(max_length=10)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('studentResponses', models.JSONField(default=list)),
            ],
        ),
    ]
