# Generated by Django 4.2 on 2023-05-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0013_studentlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogs',
            name='roll_no',
            field=models.IntegerField(),
        ),
    ]
