# Generated by Django 4.2 on 2023-05-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0014_alter_studentlogs_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogs',
            name='roll_no',
            field=models.CharField(max_length=10),
        ),
    ]
