# Generated by Django 4.2 on 2023-05-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0016_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answers',
        ),
        migrations.AddField(
            model_name='answers',
            name='answer',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
