# Generated by Django 4.2 on 2023-05-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0017_remove_answers_answers_answers_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.JSONField(default=list),
        ),
    ]
